{% extends "geodash/maps/base.yml" %}

{% block title %}
title: SPARC
{% endblock %}

{% block about %}
about:
  title: "SPARC / About"
  panes:
    - id: "about_overview"
      tab:
        label: "Overview"
      content: "**SPARC** is a Spatial Risk Calendar that combines data layers covering hazard exposure and population vulnerability to determine baseline probabilistic levels of humanitarian impact associated with particular hazard types, on a monthly basis, at a sub-national level, around the globe.\n\nSPARC is a digital service provided by the World Foood Programme (WFP), Emergency Preparedness and Support Response Division (OSE)."
    - id: "about_data"
      tab:
        label: "Data"
      content: "Data on the SPARC platform comes from many sources, including UNISDR, EM-DAT, and others.  To learn more see the info pages for each layer."
    - id: "about_help"
      tab:
        label: "Help"
      content: "To learn how to use SPARC, please see the Hands on Workshop created at: ____________."
    - id: "about_contact"
      tab:
        label: "Contact"
      content: "SPARC is a digital service provided by the World Foood Programme (WFP), Emergency Preparedness and Support Response Division (OSE).\n\nPlease contact the HQ GIS team for support at HQ[dot]GIS[at]wfp.org."
{% endblock %}

{% block welcome %}
welcome:
  title: "SPARC - Spatial Risk Calendar"
  intro: "Welcome to SPARC!\n\n SPARC is a Spatial Risk Calendar that combines data layers covering hazard exposure and population vulnerability to determine baseline probabilistic levels of humanitarian impact associated with particular hazard types, on a monthly basis, at a sub-national level, around the globe.\n\n<center>![logo](/static/sparc2/assets/img/wfp_logo_blue.png =*x*)</center>"
  about: "SPARC is a Spatial Risk Calendar that combines data layers covering hazard exposure and population vulnerability to determine baseline probabilistic levels of humanitarian impact associated with particular hazard types, on a monthly basis, at a sub-national level, around the globe.\n\nSPARC is a digital service provided by the World Food Programme (WFP), Emergency Preparedness and Support Response Division (OSE)."
{% endblock %}

{% block download %}
download:
  title: "SPARC / Download"
  panes:
    - id: "download_overview"
      tab:
        label: "Overview"
      content: "Future Information on how to download data"
    - id: "download_help"
      tab:
        label: "Help"
      content: "To learn how to use SPARC, please see the Hands on Workshop created at: ____________."
    - id: "download_contact"
      tab:
        label: "Contact"
      content: "SPARC is a digital service provided by the World Foood Programme (WFP), Emergency Preparedness and Support Response Division (OSE).\n\nPlease contact the HQ GIS team for support at HQ[dot]GIS[at]wfp.org."
{% endblock %}

{% block assets %}{% verbatim %}
assets:
  - id: "wfp_logo"
    type: image
    title: WFP logo
    #url: "https://raw.githubusercontent.com/wfp/ui/master/dist/assets/logos/light/png/2x/en-emblem.png"
    url: "/static/wfp/assets/logos/light/png/2x/en-emblem.png"
{% endverbatim %}{% endblock %}

{% block baselayers %}
baselayer: mapbox.light
baselayers:
  - id: "osm_humanitarian"
    type: xyz
    title: OpenStreetMap / Humanitarian
    description: "OpenStreetMap Basemap, Humanitarian Style"
    source:
      name: "OpenStreetMap"
      attribution: "&copy; <a href=\"http://www.openstreetmap.org/copyright\">OpenStreetMap</a>"
    tile:
      url: "http://{a-c}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png"
  - id: "osm"
    type: xyz
    title: "OpenStreetMap"
    description: "OpenStreetMap Basemap, Standard Style"
    source:
      name: "OpenStreetMap"
      attribution: "&copy; <a href=\"http://www.openstreetmap.org/copyright\">OpenStreetMap</a>"
    tile:
      url: "http://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png"
  - id: "mapbox.light"
    type: xyz
    title: "Mapbox Light"
    description: "Mapbox Basemap, Light Style"
    source:
      name: "Mapbox Light"
      attribution: "Map data &copy; <a href=\"http://openstreetmap.org\">OpenStreetMap</a> contributors, <a href=\"http://creativecommons.org/licenses/by-sa/2.0/\">CC-BY-SA</a>, Imagery &copy; <a href=\"http://mapbox.com\">Mapbox</a>"
    tile:
      url: "https://api.tiles.mapbox.com/v4/mapbox.light/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw"
  - id: "mapbox.dark"
    type: xyz
    title: "Mapbox Dark"
    description: "Mapbox Basemap, Dark Style"
    source:
      name: "Mapbox Dark"
      attribution: "Map data &copy; <a href=\"http://openstreetmap.org\">OpenStreetMap</a> contributors, <a href=\"http://creativecommons.org/licenses/by-sa/2.0/\">CC-BY-SA</a>, Imagery &copy; <a href=\"http://mapbox.com\">Mapbox</a>"
    tile:
      url: "https://api.tiles.mapbox.com/v4/mapbox.dark/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw"
{% endblock %}

{% block legendlayers %}{% endblock %}

{% block renderlayers %}
renderlayers:
  - mapbox.light
  - mapbox.dark
  - osm
  - osm_humanitarian
{% endblock %}
